set(NessDB_LIB_SEARCH_PATHS /usr/lib /usr/lib64)

find_library(NESSDB_LIBRARY
    NAMES nessdb
    HINTS ${NessDB_LIB_SEARCH_PATHS})

find_path(NESSDB_INCLUDE_DIR
    NAMES nessdb/db.h
    HINTS ${NESSDB_LIB_SEARCH_PATHS})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(NessDB
    DEFAULT_MSG NESSDB_LIBRARY NESSDB_INCLUDE_DIR)
